{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Setup Complete. Use CLIENT to access Weaviate.\n"
     ]
    }
   ],
   "source": [
    "%run \"../../../setup.ipynb\"\n",
    "if CLIENT == None:\n",
    "    print(\"Failed to create CLIENT.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "from langchain.chat_models import AzureChatOpenAI\n",
    "from langchain.vectorstores import Weaviate\n",
    "from typing import List\n",
    "import os\n",
    "import weaviate\n",
    "\n",
    "def openai_chat_client():\n",
    "  deployment = os.getenv(\"AZURE_OPENAI_LLM_DEPLOYMENT_ID\")\n",
    "  key = os.getenv(\"AZURE_OPENAI_API_KEY\")\n",
    "  resource = os.getenv(\"AZURE_OPENAI_RESOURCE_NAME\")\n",
    "\n",
    "  return AzureChatOpenAI(deployment_name=deployment, \n",
    "                         openai_api_key=key, \n",
    "                         openai_api_base=f\"https://{resource}.openai.azure.com/\",\n",
    "                         openai_api_version=\"2023-03-15-preview\")\n",
    "\n",
    "\n",
    "def weaviate_vector_store(index_name: str, text_key: str, attributes: List[str] = []):\n",
    "  weaviate_url = os.environ['WEAVIATE_URL']\n",
    "  weaviate_api_key = os.environ['WEAVIATE_API_KEY']\n",
    "  openai_api_key = os.environ['AZURE_OPENAI_API_KEY']\n",
    "\n",
    "  auth_config = weaviate.AuthApiKey(api_key=weaviate_api_key)\n",
    "\n",
    "  client = weaviate.Client(\n",
    "      url=weaviate_url,\n",
    "      auth_client_secret=auth_config,\n",
    "      additional_headers={\n",
    "          \"X-OpenAI-Api-Key\": openai_api_key\n",
    "      }\n",
    "  )\n",
    "  return Weaviate(client=client, \n",
    "                  index_name=index_name, \n",
    "                  text_key=text_key, \n",
    "                  attributes=attributes)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "from langchain.agents.agent_toolkits import (\n",
    "    create_vectorstore_agent,\n",
    "    VectorStoreToolkit,\n",
    "    VectorStoreInfo,\n",
    ")\n",
    "\n",
    "weaviate = weaviate_vector_store(index_name=\"Work\", \n",
    "                                 text_key=\"title\", \n",
    "                                 attributes=[\"identifier\", \"source\", \"title\"])\n",
    "\n",
    "vectorstore_info = VectorStoreInfo(\n",
    "    name=\"Work\",\n",
    "    description=\"NULDC Works\",\n",
    "    vectorstore=weaviate,\n",
    ")\n",
    "llm = openai_chat_client()\n",
    "toolkit = VectorStoreToolkit(vectorstore_info=vectorstore_info, llm=llm)\n",
    "agent_executor = create_vectorstore_agent(llm=llm, toolkit=toolkit, verbose=True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\u001b[1m> Entering new  chain...\u001b[0m\n",
      "\u001b[32;1m\u001b[1;3mI should use the Work tool to find information about John Cage's correspondence.\n",
      "Action: Work\n",
      "Action Input: John Cage's correspondence\u001b[0m\n",
      "Observation: \u001b[36;1m\u001b[1;3mI'm sorry, but I would need more information to answer your question. Which specific correspondence of John Cage are you referring to?\u001b[0m\n",
      "Thought:Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 377, in _make_request\n",
      "    httplib_response = conn.getresponse(buffering=True)\n",
      "TypeError: getresponse() got an unexpected keyword argument 'buffering'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3505, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_6427/2344850719.py\", line 1, in <module>\n",
      "    agent_executor.run(\"What can you tell me about John Cage's correspondence?\")\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/langchain/chains/base.py\", line 290, in run\n",
      "    return self(args[0], callbacks=callbacks, tags=tags)[_output_key]\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/langchain/chains/base.py\", line 166, in __call__\n",
      "    raise e\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/langchain/chains/base.py\", line 160, in __call__\n",
      "    self._call(inputs, run_manager=run_manager)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/langchain/agents/agent.py\", line 957, in _call\n",
      "    **tool_run_kwargs,\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/langchain/agents/agent.py\", line 762, in _take_next_step\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/langchain/agents/agent.py\", line 443, in plan\n",
      "    full_output = self.llm_chain.predict(callbacks=callbacks, **full_inputs)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/langchain/chains/llm.py\", line 252, in predict\n",
      "    return self(kwargs, callbacks=callbacks)[self.output_key]\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/langchain/chains/base.py\", line 166, in __call__\n",
      "    raise e\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/langchain/chains/base.py\", line 160, in __call__\n",
      "    self._call(inputs, run_manager=run_manager)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/langchain/chains/llm.py\", line 92, in _call\n",
      "    response = self.generate([inputs], run_manager=run_manager)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/langchain/chains/llm.py\", line 102, in generate\n",
      "    return self.llm.generate_prompt(\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/langchain/chat_models/base.py\", line 167, in generate_prompt\n",
      "    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/langchain/chat_models/base.py\", line 102, in generate\n",
      "    raise e\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/langchain/chat_models/base.py\", line 94, in generate\n",
      "    results = [\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/langchain/chat_models/base.py\", line 95, in <listcomp>\n",
      "    self._generate(m, stop=stop, run_manager=run_manager, **kwargs)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/langchain/chat_models/openai.py\", line 359, in _generate\n",
      "    response = self.completion_with_retry(messages=message_dicts, **params)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/langchain/chat_models/openai.py\", line 307, in completion_with_retry\n",
      "    return _completion_with_retry(**kwargs)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/tenacity/__init__.py\", line 289, in wrapped_f\n",
      "    return self(f, *args, **kw)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/tenacity/__init__.py\", line 379, in __call__\n",
      "    do = self.iter(retry_state=retry_state)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/tenacity/__init__.py\", line 314, in iter\n",
      "    return fut.result()\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/concurrent/futures/_base.py\", line 439, in result\n",
      "    return self.__get_result()\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/concurrent/futures/_base.py\", line 391, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/tenacity/__init__.py\", line 382, in __call__\n",
      "    result = fn(*args, **kwargs)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/langchain/chat_models/openai.py\", line 305, in _completion_with_retry\n",
      "    return self.client.create(**kwargs)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/openai/api_resources/chat_completion.py\", line 25, in create\n",
      "    return super().create(*args, **kwargs)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py\", line 153, in create\n",
      "    response, _, api_key = requestor.request(\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/openai/api_requestor.py\", line 288, in request\n",
      "    result = self.request_raw(\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/openai/api_requestor.py\", line 596, in request_raw\n",
      "    result = _thread_context.session.request(\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/requests/sessions.py\", line 587, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/requests/sessions.py\", line 701, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/requests/adapters.py\", line 489, in send\n",
      "    resp = conn.urlopen(\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 597, in urlopen\n",
      "    httplib_response = self._make_request(conn, method, url,\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 380, in _make_request\n",
      "    httplib_response = conn.getresponse()\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/http/client.py\", line 1377, in getresponse\n",
      "    response.begin()\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/http/client.py\", line 320, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/http/client.py\", line 281, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/socket.py\", line 704, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/ssl.py\", line 1242, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/ssl.py\", line 1100, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2102, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1310, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1199, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1052, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 978, in format_exception_as_a_whole\n",
      "    frames.append(self.format_record(record))\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 878, in format_record\n",
      "    frame_info.lines, Colors, self.has_colors, lvals\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 712, in lines\n",
      "    return self._sd.lines\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/stack_data/core.py\", line 698, in lines\n",
      "    pieces = self.included_pieces\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/stack_data/core.py\", line 649, in included_pieces\n",
      "    pos = scope_pieces.index(self.executing_piece)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/stack_data/core.py\", line 628, in executing_piece\n",
      "    return only(\n",
      "  File \"/home/ec2-user/.conda/envs/weaviate/lib/python3.9/site-packages/executing/executing.py\", line 164, in only\n",
      "    raise NotOneValueFound('Expected one value, found 0')\n",
      "executing.executing.NotOneValueFound: Expected one value, found 0\n"
     ]
    }
   ],
   "source": [
    "agent_executor.run(\"What can you tell me about John Cage's correspondence?\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "weaviate",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
